# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tablesample.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Table(object):
    def setupUi(self, Table):
        Table.setObjectName("Table")
        Table.resize(303, 221)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Table.sizePolicy().hasHeightForWidth())
        Table.setSizePolicy(sizePolicy)
        Table.setMinimumSize(QtCore.QSize(303, 221))
        Table.setMaximumSize(QtCore.QSize(303, 221))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Table)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Table)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.spin_frame = QtWidgets.QFrame(self.frame)
        self.spin_frame.setGeometry(QtCore.QRect(50, 60, 91, 61))
        self.spin_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.spin_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.spin_frame.setObjectName("spin_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.spin_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.column = QtWidgets.QSpinBox(self.spin_frame)
        self.column.setStyleSheet("")
        self.column.setObjectName("column")
        self.verticalLayout.addWidget(self.column)
        self.Row = QtWidgets.QSpinBox(self.spin_frame)
        self.Row.setStyleSheet("")
        self.Row.setObjectName("Row")
        self.verticalLayout.addWidget(self.Row)
        self.column_lable = QtWidgets.QLabel(self.frame)
        self.column_lable.setGeometry(QtCore.QRect(200, 70, 61, 21))
        self.column_lable.setObjectName("column_lable")
        self.Row_lable = QtWidgets.QLabel(self.frame)
        self.Row_lable.setGeometry(QtCore.QRect(200, 100, 61, 21))
        self.Row_lable.setObjectName("Row_lable")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame)
        self.buttonBox.setGeometry(QtCore.QRect(50, 150, 193, 28))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Table)
        QtCore.QMetaObject.connectSlotsByName(Table)

    def retranslateUi(self, Table):
        _translate = QtCore.QCoreApplication.translate
        Table.setWindowTitle(_translate("Table", "Dialog"))
        self.column_lable.setText(_translate("Table", "Column"))
        self.Row_lable.setText(_translate("Table", "Row"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Table = QtWidgets.QDialog()
    ui = Ui_Table()
    ui.setupUi(Table)
    Table.show()
    sys.exit(app.exec_())
